#!/usr/bin/bash
#
# Put customizations to your image in this file.

# Custom versions and variables
PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin
SDC_IMGAPI_VERSION='20150219'

# Exit if any commands fail
set -o errexit

# Configuring image specific packages
echo "* Configuring image specific packages.";

echo "* Download and extract imgapi"
mkdir -p /opt/imgapi
curl -L https://github.com/joyent/sdc-imgapi/archive/${SDC_IMGAPI_VERSION}.tar.gz | tar xz -C /opt/imgapi --strip-components=1

echo "* Workaround for npm install usage with git repo"
sed -i 's|ssh://git@github.com:\(.*\).git\(.*\)|https://github.com/\1\2|g' \
	/opt/imgapi/package.json

echo "* Change working directory"
cd /opt/imgapi/

echo "* More workaround to install some deps manually"
npm install fast
npm install ldapjs
npm install git+https://github.com/joyent/node-ufds

echo "* Run npm install to get the requirements, ignore errors"
npm install . || true

echo "* Install template config file"
mv /tmp/imgapi.config.tpl /opt/imgapi/etc/

echo "* Import imgapi manifest"
svccfg import /tmp/imgapi.xml
rm /tmp/imgapi.xml

# Clean up
echo "* Cleaning up."
rm -rf /root/*

# Prepare image for provisioning
sm-prepare-image -y
